language: php
php:
 - 5.6
 - 5.5
 - 5.4
env:
 - DB=mysql
 
before_script:
 - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS lilurlshortener;" -uroot; fi
install:
 - composer install
 
branches:
  except:
    - master